#!/usr/bin/env bash
# Rebuild this film's soundtrack from source: the English narration (audio/voiceover.en.flac, the lossless master of the
# Gemini TTS takes, which cannot be regenerated byte for byte), foley (tools/foley.py → audio/events.json + audio/sfx/),
# the score (audio/score.json → bin/vh music), the mix (−14 LUFS, the music ducked under the voice), the audio QA, and
# optionally the mux with a soft English subtitle track.
#   showcase/03-math-fourier/tools/build_audio.sh                   → audio/mix.wav + audio/qa.txt
#   showcase/03-math-fourier/tools/build_audio.sh --no-sonify       … without the partial-sum tones ("layer": "sonification")
#   showcase/03-math-fourier/tools/build_audio.sh --mux out.mp4     … and out.mp4 = media/final.mp4's picture + the mix + subs
# Needs uv, ffmpeg and the repo's bin/vh.
set -euo pipefail
FILM=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
VH="$FILM/../../bin/vh"
A="$FILM/audio"
DUR=25 FPS=30 FADE=0.5          # the film's length; the last chord is faded over the last FADE s
OFFSET=0.3                      # the score's beat 0 is 0.3 s into the film (the first line starts there)
VO_LANG=en MUSIC_DB=-5          # narration language; music level before the mix ducks it under the voice (ratio 1.6)
PAD=3                           # every bus runs PAD s past the film and the mix is cut afterwards (see step 4)
sonify=1 out=""
while [ $# -gt 0 ]; do
  case $1 in
    --no-sonify) sonify=0 ;;
    --mux) out=${2:?--mux needs an output path}; shift ;;
    *) echo "usage: $0 [--no-sonify] [--mux out.mp4]" >&2; exit 2 ;;
  esac
  shift
done
calc() { python3 -c "print(round($1, 3))"; }
LEN=$(calc "$DUR + $PAD")
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

# 1 narration: decode the committed master (bit-exact PCM), padded with silence to the buses' length
ffmpeg -v error -y -i "$A/voiceover.$VO_LANG.flac" -af "apad=whole_dur=$LEN" "$A/voiceover.$VO_LANG.wav"
# 2 foley: custom sounds + event list, the 15 built-ins beside them, then one stereo SFX track
uv run -q --with numpy --with scipy python "$FILM/tools/foley.py"
"$VH" sfx lib "$A/sfx" >/dev/null
ev="$A/events.json"
if [ "$sonify" = 0 ]; then
  ev="$tmp/events.json"
  python3 -c 'import json, sys; e = json.load(open(sys.argv[1])); json.dump([x for x in e if x.get("layer") != "sonification"], open(sys.argv[2], "w"), ensure_ascii=False, indent=1)' "$A/events.json" "$ev"
fi
"$VH" sfx place "$ev" "$A/sfx.wav" "$LEN" --lib "$A/sfx"
# 3 music: render the score and start it OFFSET s into the film; shift its beat map to film time
"$VH" music "$A/score.json" "$A/score.wav"
ffmpeg -v error -y -i "$A/score.wav" -af "adelay=delays=$(calc "$OFFSET * 1000"):all=1,atrim=0:$LEN" "$A/music.wav"
python3 - "$A/score.beats.json" "$A/music.beats.json" "$OFFSET" <<'PY'
import json, sys
bm, d = json.load(open(sys.argv[1])), float(sys.argv[3])
sh = lambda t: round(t + d, 3)
bm.update(offset=d, beats=[sh(t) for t in bm["beats"]], downbeats=[sh(t) for t in bm["downbeats"]],
          sections=[dict(s, start=sh(s["start"]), end=sh(s["end"])) for s in bm["sections"]],
          hits=[dict(h, t=sh(h["t"])) for h in bm["hits"]], duration=sh(bm["duration"]))
if "bars" in bm:
    bm["bars"] = [[b, sh(t), n] for b, t, n in bm["bars"]]
bm["note"] = f"film time: the score starts {d} s into the film (tools/build_audio.sh)"
json.dump(bm, open(sys.argv[2], "w"), indent=1)
PY
rm -f "$A/score.wav" "$A/score.beats.json"
# 4 mix at −14 LUFS: the voice ducks the music (duck_ratio 1.6, playbook/04 default); one static gain. Then cut to the
#   film with a short fade. The buses run PAD s past the film because with ffmpeg 8.0.1 the last ~1.2 s of a `bin/vh mix`
#   output changed from run to run (zeroed or garbled near the end of the streams, after the ducker); the film itself
#   then comes out the same every time.
"$VH" mix "$A/mix.full.wav" voice="$A/voiceover.$VO_LANG.wav" music="$A/music.wav" sfx="$A/sfx.wav" \
  music_db="$MUSIC_DB" duck=voice duck_ratio=1.6
ffmpeg -v error -y -i "$A/mix.full.wav" -af "atrim=0:$DUR,afade=t=out:st=$(calc "$DUR - $FADE"):d=$FADE" "$A/mix.wav"
rm -f "$A/mix.full.wav"
# the cut moves the integrated loudness a little (the second past the film is gone): if it is now louder, one static
# gain brings it back to −14 (a cut never makes it much quieter; that case is only reported)
python3 - "$A/mix.wav" <<'PY'
import json, re, shutil, subprocess, sys
p = sys.argv[1]
def meter(f):
    err = subprocess.run(["ffmpeg", "-hide_banner", "-nostats", "-i", f, "-af", "loudnorm=print_format=json", "-f", "null", "-"],
                         capture_output=True, text=True, check=True).stderr
    return json.loads(re.search(r"\{[^{}]*\"input_i\"[^{}]*\}", err, re.S).group(0))
g = -14 - float(meter(p)["input_i"])
if g < -0.05:
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", p, "-af", f"volume={g:.2f}dB", p + ".tmp.wav"], check=True)
    shutil.move(p + ".tmp.wav", p)
m = meter(p)
print(f"  mix.wav: {m['input_i']} LUFS, true peak {m['input_tp']} dBTP, LRA {m['input_lra']} LU")
PY
# 5 QA on the mix (the designed dip under the voice is not counted as pumping)
qa=0
"$VH" qa "$A/mix.wav" "$A/music.beats.json" "$ev" --fps "$FPS" --to "$(calc "$DUR - 0.3")" \
  --voice "$A/voiceover.$VO_LANG.wav" --out "$A/qa.txt" || qa=$?
# 6 optional: the picture of media/final.mp4 (video stream only) + this mix + a soft subtitle track (en)
if [ -n "$out" ]; then "$VH" mux "$FILM/media/final.mp4" "$A/mix.wav" "$out" "$A/captions.en.srt"; fi
exit "$qa"
