#!/usr/bin/env bash
# Rebuild this film's soundtrack from source: the English narration (audio/voiceover.en.flac, the lossless master of the
# Gemini TTS takes, which cannot be regenerated byte for byte), foley (tools/foley.py → audio/events.json + audio/sfx/),
# the score (audio/score.json → bin/vh music), the mix (bin/vh mix profile=explainer, −14 LUFS), the audio QA with the
# mix report, and optionally the mux with a soft English subtitle track.
#   showcase/03-math-fourier/tools/build_audio.sh                   → audio/mix.wav, audio/stems/, audio/qa.txt
#   showcase/03-math-fourier/tools/build_audio.sh --mux out.mp4     … and out.mp4 = media/final.mp4's picture + the mix + en subs
# Needs uv, ffmpeg and the repo's bin/vh. The same sources give the same bytes: the profile mix has no ffmpeg filter in
# its signal path and seeds its room.
set -euo pipefail
FILM=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
VH="$FILM/../../bin/vh"
A="$FILM/audio"
DUR=25 FPS=30 FADE=0.5          # the film's length; the last chord is faded over the last FADE s inside the mix
OFFSET=0.3                      # the score's beat 0 is 0.3 s into the film (the first line starts there)
VO_LANG=en                      # the narration's language: audio/voiceover.en.flac, audio/timeline.en.json
PROFILE=explainer               # playbook/04-audio.md, 混音: maths explainer, the narration is the programme (VMR 13 LU)
MUSIC_DB=-5                     # the starting balance (with narration the music's level comes from the VMR, not from this)
TP=-1.65                        # the mix's true-peak ceiling; lowered when the AAC encode peaks over −1.5 dBTP (step 6)
SUBS=("$A/captions.en.srt")     # the soft subtitle track (bin/vh mux names it eng)
out=""
while [ $# -gt 0 ]; do
  case $1 in
    --mux) out=${2:?--mux needs an output path}; shift ;;
    *) echo "usage: $0 [--mux out.mp4]" >&2; exit 2 ;;
  esac
  shift
done
calc() { python3 -c "print(round($1, 3))"; }
if [ -n "$out" ]; then   # the picture is read from media/final.mp4: writing over it while reading it would destroy it
  case "$out" in /*) ;; *) out="$PWD/$out" ;; esac
  [ "$(cd "$(dirname "$out")" && pwd -P)/$(basename "$out")" != "$(cd "$FILM/media" && pwd -P)/final.mp4" ] \
    || { echo "--mux: write to another file, then move it over media/final.mp4" >&2; exit 2; }
fi
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

# 1 narration: decode the committed master (bit-exact PCM), and cut each line from it (audio/vo/<lang>/NN.wav, the
#   files timeline.<lang>.json names: what `bin/vh tts --resume` and a re-alignment read)
ffmpeg -v error -y -i "$A/voiceover.$VO_LANG.flac" "$A/voiceover.$VO_LANG.wav"
python3 - "$A/voiceover.$VO_LANG.wav" "$A/timeline.$VO_LANG.json" "$FILM" <<'PY'
import json, os, sys, wave
src, tl, film = sys.argv[1:4]
with wave.open(src, "rb") as w:
    p, sr, width, pcm = w.getparams(), w.getframerate(), w.getsampwidth() * w.getnchannels(), w.readframes(w.getnframes())
for s in json.load(open(tl, encoding="utf-8"))["segments"]:
    a, b = round(s["start"] * sr), round(s["end"] * sr); dst = os.path.join(film, s["file"])
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with wave.open(dst, "wb") as o:
        o.setparams(p); o.writeframes(pcm[a * width:b * width])
PY
# 2 foley: the custom sounds + the event list, and the 15 built-ins beside them (the mix places every event itself)
uv run -q --no-project --with numpy --with scipy python "$FILM/tools/foley.py"   # --no-project: run from 03's folder, uv would sync its Manim env
"$VH" sfx lib "$A/sfx" >/dev/null
# 3 music: render the score and start it OFFSET s into the film; shift its beat map to film time
"$VH" music "$A/score.json" "$tmp/score.wav" >/dev/null
ffmpeg -v error -y -i "$tmp/score.wav" -af "adelay=delays=$(calc "$OFFSET * 1000"):all=1" "$A/music.wav"
python3 - "$tmp/score.beats.json" "$A/music.beats.json" "$OFFSET" <<'PY'
import json, sys
bm, d = json.load(open(sys.argv[1])), float(sys.argv[3])
sh = lambda t: round(t + d, 3)
bm.update(offset=d, beats=[sh(t) for t in bm["beats"]], downbeats=[sh(t) for t in bm["downbeats"]],
          sections=[dict(s, start=sh(s["start"]), end=sh(s["end"])) for s in bm["sections"]],
          hits=[dict(h, t=sh(h["t"])) for h in bm["hits"]], duration=sh(bm["duration"]))
if "bars" in bm:
    bm["bars"] = [[b, sh(t), n] for b, t, n in bm["bars"]]
bm["note"] = f"film time: the score starts {d} s into the film (tools/build_audio.sh)"
json.dump(bm, open(sys.argv[2], "w"), indent=1)
PY
# 4 mix: profile explainer. The narration is the anchor (each line levelled toward the median line); the music is ridden
#   under every line to the profile's voice-to-music ratio, with a presence carve only as deep as the words need; each
#   SFX event is classed (the partial-sum tones: "layer": "sonification" → signal) and moved half way to its
#   class's range; one short room behind the SFX; cut to the film inside the mix with a FADE s fade; one static gain to
#   −14 LUFS, true peak ≤ TP.
mix() {
  "$VH" mix "$A/mix.wav" profile=$PROFILE voice="$A/voiceover.$VO_LANG.wav" timeline="$A/timeline.$VO_LANG.json" \
    music="$A/music.wav" events="$A/events.json" lib="$A/sfx" dur=$DUR fade=$FADE music_db=$MUSIC_DB tp="$TP" stems="$A/stems" \
    > "$A/mix.log" || { cat "$A/mix.log"; exit 1; }
  tail -1 "$A/mix.log"
}
# 5 QA on the mix (the gate): silence, dropouts, pumping (the designed dips under the voice and the score's own dips,
#   both known from the stems, excluded), clicks, every cue (score hits + SFX events) within one frame, and the mix report
#   (qa mix: VMR per line, the words at risk, the SFX classes, depth)
qa() { # $1 = file, $2 = report
  local rc=0
  "$VH" qa "$1" "$A/music.beats.json" "$A/events.json" --fps $FPS --to "$(calc "$DUR - $FADE")" --stems "$A/stems" --out "$2" \
    > "$2.log" 2>&1 || rc=$?
  tail -1 "$2.log"; return $rc
}
mix
rc=0; qa "$A/mix.wav" "$A/qa.txt" || rc=$?
# 6 optional: the picture of media/final.mp4 (its video stream, copied) + the mix as AAC 192k + the soft subtitle tracks.
#   The encode raises the true peak by an amount that depends on the content, so it is measured with the mixer's own 4×
#   meter; over −1.5 dBTP the mix is made again with its ceiling below its own true peak by the overshoot + 0.1 dB (at
#   most 3 times), then the mp4 gets the scan and the cue check too (its cue problems only warn, unless the whole encode
#   is off: a mux offset). A mix that fails its QA is not muxed.
if [ -n "$out" ] && [ "$rc" != 0 ]; then
  echo "  not muxed: the mix failed its QA (see $A/qa.txt)" >&2
elif [ -n "$out" ]; then
  k=0
  while :; do
    "$VH" mux "$FILM/media/final.mp4" "$A/mix.wav" "$out" "${SUBS[@]}" >/dev/null
    etp=$(uv run -q --no-project --with numpy --with scipy python -c "import sys; sys.path.insert(0, sys.argv[1]); import mix; print(f'{mix.true_peak(mix.load(sys.argv[2])):.2f}')" \
          "$FILM/../../tools/audio" "$out")
    python3 -c "import sys; sys.exit(0 if float(sys.argv[1]) <= -1.5 else 1)" "$etp" && break
    [ $k -lt 3 ] || { echo "the AAC encode still peaks at $etp dBTP after 3 new mixes (tp=$TP)" >&2; exit 1; }
    k=$((k + 1)); TP=$(python3 -c "import json, sys; m = json.load(open(sys.argv[3]))['tp']
print(f'{min(float(sys.argv[1]), m) - (float(sys.argv[2]) + 1.5) - 0.1:.2f}')" "$TP" "$etp" "$A/stems/meta.json")
    echo "  the AAC encode peaks at $etp dBTP: mixing again with tp=$TP"
    mix; qa "$A/mix.wav" "$A/qa.txt" || { echo "  not muxed: the new mix failed its QA (see $A/qa.txt)" >&2; rm -f "$out"; exit 1; }
  done
  echo "  $out: AAC true peak $etp dBTP (mix tp $TP)"
  qa "$out" "$A/qa_mp4.txt" || rc=$?
fi
exit "$rc"
